### ISSUE TITLE
GLFW: An uncaught error has occurred: APIUnavailable: GLX: No GLXFBConfigs returned 

### ISSUE THREAD

**Issue by knightpp** [go-gl/glfw3#347]
```
XGB: conn.go:47: Could not get authority info: open /home/username/.Xauthority: no such file or directory
XGB: conn.go:48: Trying connection without authority info...
GLFW: An uncaught error has occurred: APIUnavailable: GLX: No GLXFBConfigs returned
GLFW: Please report this bug in the Go package immediately.
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: GLX: Failed to find a suitable GLXFBConfig
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: GLX: Failed to find a suitable GLXFBConfig

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0xc0000c5cc8, 0x2, 0x2188c08763d0})
	/home/username/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/error.go:178 +0x177
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x493086, 0xc0000c5d58, {0x0, 0x492f34}, 0x0, 0x0)
	/home/username/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/window.go:350 +0x170
github.com/hajimehoshi/ebiten/v2/internal/glfw.CreateWindow(0xc0000c5d80, 0x0, {0x0, 0x493060}, 0x8f7e90, 0xc0000c5d70)
	/home/username/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.4/internal/glfw/glfw_notwindows.go:261 +0x3d
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).createWindow(0x810bc0)
	/home/username/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.4/internal/uidriver/glfw/ui.go:732 +0x45
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).init(0x810bc0)
	/home/username/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.4/internal/uidriver/glfw/ui.go:926 +0x13f
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run.func1.2()
	/home/username/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.4/internal/uidriver/glfw/run_notsinglethread.go:47 +0x1d
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000312720)
	/home/username/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.4/internal/thread/thread.go:51 +0x77
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0x810bc0, {0x6a5630, 0x8a5ea0})
	/home/username/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.4/internal/uidriver/glfw/run_notsinglethread.go:60 +0x1bf
github.com/hajimehoshi/ebiten/v2.RunGame({0x6a3488, 0x8f7ca0})
	/home/username/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.4/run.go:160 +0xf9
main.main()
	/home/username/Projects/Go/ebiten-test/main.go:27 +0x49
exit status 2
```
I wanted to build Ebiten hello world example, but I'm using nix to manage X11 dependencies. Building and running executable gives the above output.

To build and run, I do the following: ( https://github.com/knightpp/ebiten-glfw-bug-nix )
```
# Inside repo
nix-shell --pure
# usual go commands
go build -o app .
# note: in the host shell I see the same error
./app
```

**Comment by knightpp** [comment]
It's an issue with nix. It handles OpenGL in different way. To fix, I had to use https://github.com/guibou/nixGL.
