### ISSUE TITLE
Crash during Init() when using race detector

### ISSUE THREAD

**Issue by bitdriftr** [go-gl/glfw3#348]
When using the go race detector (`-race` flag on build), the `glfw.Init()` function randomly hangs or crash.

Considering the following sample program :
```go
package main

import (
	"runtime"

	"github.com/go-gl/glfw/v3.3/glfw"
)

func init() {
	runtime.LockOSThread()
}

func main() {
	err := glfw.Init()
	if err != nil {
		panic(err)
	}

	defer glfw.Terminate()
}
```

When running with `-race` it runs properly in 80% cases, but randomly either hangs forever or crash with this trace :

```
sample(42367,0x10189c580) malloc: Heap corruption detected, free list is damaged at 0x600001000240
*** Incorrect guard value: 0
daw(42367,0x10189c580) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x19cfb99b8 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x100a38dcc, 0xc0000a5e98, 0xc0000a5e88)
	/usr/local/go/root/src/runtime/cgocall.go:154 +0x68 fp=0xc0000a5e60 sp=0xc0000a5e20 pc=0x10096b198
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwInit(0xc000000000)
	_cgo_gotypes.go:1396 +0x58 fp=0xc0000a5e90 sp=0xc0000a5e60 pc=0x100a25a98
github.com/go-gl/glfw/v3.3/glfw.Init(0xc000048768, 0x10099a434)
	/usr/local/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211213063430-748e38ca8aec/glfw.go:36 +0x24 fp=0xc0000a5ef0 sp=0xc0000a5e90 pc=0x100a265e4
main.main()
	/path/to/repo/cmd/daw/main.go:19 +0x24 fp=0xc0000a5f70 sp=0xc0000a5ef0 pc=0x100a282f4
runtime.main()
	/usr/local/go/root/src/runtime/proc.go:225 +0x26c fp=0xc0000a5fd0 sp=0xc0000a5f70 pc=0x10099a46c
runtime.goexit()
	/usr/local/go/root/src/runtime/asm_arm64.s:1130 +0x4 fp=0xc0000a5fd0 sp=0xc0000a5fd0 pc=0x1009c9124

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x1
r7      0x128ae0028
r8      0xd223c5dbf6f9927a
r9      0xd223c5daf77057fa
r10     0xcccccccccccccccd
r11     0xa
r12     0x0
r13     0x34
r14     0x1200000
r15     0x600002b01c80
r16     0x148
r17     0x1f77cb530
r18     0x0
r19     0x6
r20     0x10189c580
r21     0x103
r22     0x16f49ab80
r23     0x128ae0000
r24     0x0
r25     0x0
r26     0x16f49b95d
r27     0x10189c580
r28     0x4
r29     0x16f49aa90
lr      0x19cfeceb0
sp      0x16f49aa70
pc      0x19cfb99b8
fault   0x19cfb99b8
exit status 2
```

This does not reproduce without the `-race` flag.

Host : Mac M1 running Monterey
`Darwin hostname 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64`

Tested using go 1.16 and 1.17.3.

**Comment by Jacalz** [comment]
I can not replicate this now. Has likely either been fixed in this project, the Go compiler itself or the race detector. I'll close this for now but feel free to reopen if the issue persists.
